title: Tuspe Design
phone: 040 774 6121
phone_link: "+358407746121"
email: info@tuspe.com
street: Lehtikuusentie 5 B 35
postal: 26100
area: Rauma
region: Satakunta
latitude: 61.125934
longitude: 21.532696
map: https://goo.gl/maps/xkRMUVUmoqYp1Taj8
url: "https://tuspe.com"
twitter_site: tuspedesign
twitter_creator: tewdin
github_username:  tewdin

theme: minima
plugins:
  - jekyll-gzip

social:
  - name: linkedin
    url: https://www.linkedin.com/in/anttilatimo/
  - name: facebook
    url: https://www.facebook.com/tuspedesign
  - name: twitter
    url: https://twitter.com/tuspedesign
  - name: github
    url: https://github.com/tewdin

footer: "Living, learning, &amp; leveling up<br>one day at a time."

hire:
  en: "Hire me"
  fi: "Ota yhteyttä"

more:
  en: "Read more"
  fi: "Lue lisää"

include:
  - _headers

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md