
title: Tuspe Design
base: https://tuspe.com

# Build settings
markdown: kramdown
theme: minima

social:
  - name: linkedin
    alt: "LinkedIn: Timo Anttila"
    url: https://www.linkedin.com/in/anttilatimo/
  - name: facebook
    alt: "Facebook: Tuspe Design"
    url: https://www.facebook.com/tuspedesign
  - name: twitter
    alt: "Twitter: Tuspe Design"
    url: https://twitter.com/tuspedesign
  - name: github
    alt: "Github: Timo Anttila"
    url: https://github.com/timoanttila

contact:
  phone: "+358407746121"
  email: "info@tuspe.com"
  street: "Lehtikuusentie 5 B 35"
  postal: "26100"
  area: "Rauma"
  latitude: "61.125934"
  longitude: "21.532696"
  map: "https://goo.gl/maps/xkRMUVUmoqYp1Taj8"

defaults:
  - scope:
      path: ""
    values:
      lang: "fi"
      layout: default
  - scope:
      path: "en"
    values:
      lang: "en"

img: "https://tuspe.com/assets/images/hero.jpg"

fi:
  title: "Tuspe Design | Verkkosivut yrityksille"
  summary: "Tuspe on raumalainen verkkosivustojen ja verkkokauppojen suunnitteluun ja toteutukseen sekä asiantuntevaan Google-hakukoneoptimointiin erikoistunut yritys."
  hello_title: "Hei, olen Timo. Hauska tavata."
  hello_body: "<p>Olen rakentanut verkkosivustoja ja -kauppoja yrityksille ja yhteisöille vuodesta 2014, jonka aikana olen tehnyt etätöitä mainostoimistoille, konsultoinut yrityksiä, luonut satoja verkkosivustoja sekä kehittänyt kumppanien kanssa verkkokaupan, varauskalenterin ja urheilualustan ProcessWirelle. Verkostosta löytyy tarvittaessa tekijöitä myös markkinointiin, yrityksen tai tuotteiden brändäykseen, grafiikkaan sekä sisällön tuottamiseen.</p><p>Käytettävissä etätyöhön sekä Rauman keskustassa toimistolla tai asiakkaan tiloissa.<br>Etsin mainostoimistoja verkostoon. <a href=mailto:info@tuspe.com rel=nofollow title=\"Lähetä sähköpostia\">Ota rohkeasti yhteyttä</a> jos kaipaat verkkosivustoa tai yhteistyö kiinnostaa.</p>"
  featured:
    - title: Verkkotohtorointi
      body: "Kaipaako yrityksesi uutta verkkosivustoa tai vanha huoltotoimenpiteitä? Toteutan kaikki projektit ketterästi ja kilpailukykyisellä hinnalla 'avaimet käteen'-periaatteella asiakkaan kaikkien toiveiden mukaisesti. Uusi verkkosivusto on responsiivinen, hakukoneoptimoitu, nopea ja helposti päivitettävä."
      img: websites
      img_alt: "Responsiiviset ja kauniit verkkosivut yritykselle"
    - title: Verkkokaupat
      body: "Tehosta myyntiä Tuspen monipuolisella verkkokaupalla Suomessa ja ulkomailla kilpailukykyiseen hintaan. Verkkokauppa kustomoidaan vastaamaan asiakkaan tarpeita, jonka lisäksi kaupassa on tarjolla rajattomasti kieli, tehokkaat kampanjat sekä tietenkin yleisimmät maksuvaihtoehdot ja kuljetukset."
      img: webshops
      img_alt: "Tehosta myyntiä paremmalla verkkokaupalla"
    - title: Ratsukko
      body: "Oletko saanut tarpeeksi soitoista ja sähköposteista talliyrittäjänä tai tallin asiakkaana? Ei hätää! Varauskalenteri Ratsukko säästää aikaa ja vaivaa tarjoten reaaliaikaisen järjestelmän missä asiakkaat voivat itse hoitaa tuntien varaukset ja poistot. Hyppää ratsaille kohti helpompaa arkea!"
      img: ratsukko
      img_alt: "Varauskalenteri Ratsukko säästää aikaa, vaivaa ja rahaa!"
    - title: Urheiluseurat
      body: "Monipuolisilla ominaisuuksilla varustettu urheilualusta sopii kaiken kokoisille urheiluseuroille. Tarvittaessa mukaan myös verkkokauppa. Päivitys helppoa ja nopeaa sekä olemme automatisoineet mahdollisimman paljon toimintoja. Oletko valmis lähtemään mukaan voittajan tiimiin?"
      img: sport
      img_alt: "Monipuolinen kotisivu urheiluseuralle"
    - title: Hakukoneoptimointi
      body: "Kaikki projektit on teknisesti optimoitu hakukoneille ja vierailijoille, mutta sisältö on tärkein ja sen pitää olla uniikkia! Tarjoan vinkkejä miten voisit paremmin optimoida verkkosivustosi sekä verkoston kautta löytyy myös tarvittaessa ammattilainen kehittämään verkkosivuston sisältöä."
      img: seo
      img_alt: "Tietoa teknisestä hakukoneoptimoinnista ja hakusanatutkimuksesta"
    - title: Ylläpito
      body: "Dedikoidut palvelimme on suojattu teknisiltä ongelmilta sekä kaikki data varmuuskopioidaan kahdesti päivässä ulkoiselle palvelimelle. Turvallinen ja luotettava koti verkkosivustolle sekä samaan hintaan turvallisuuspäivitykset moduuleille ja pienet muutokset verkkosivustolle."
      img: hosting
      img_alt: "Turvallinen ja luotettava koti verkkosivulle"
  atom: "Viimeisimmät lisäykset lähdekoodiin"
  footer:
    left: "Uusi projekti?"
    mid: "Kiinnostaako yhteistyö? Ota yhteyttä ja keskustellaan miten voin auttaa."

en:
  title: "Tuspe Design | Responsive and beautiful websites"
  summary: "Tuspe is a Rauma based company specialized in designing and implementing websites and e-commerce stores as well as expert Google search engine optimization."
  hello_title: "Hey, I'm Timo. Nice to meet you."
  hello_body: "<p>I've designed and created websites for several communities and my own needs since 1999. I started to make websites for living in 2014 when Molentum Oy hired me. A couple of years later, in 2016, I founded my own company Tuspe and nowadays I work full time through Tuspe for Molentum. Time to time I do some projects for Dataline (web shops and sport platforms) and develop Ratsukko booking system for SatuMo Oy.</p><p>My specialities are HTML5, CSS3, AMP HTML -mobile optimization technique, PHP and search engine optimization. I also have basic knowlegde of photography, photo editing and video creation. I follow the latest trends from the world, and by that my customers can be the forerunners in their field and communicate in a modern way. My goal is satisfied customers and long customer relationships and offer 100% satisfaction guarantee for all of my projects.</p><p><a href=mailto:info@tuspe.com rel=nofollow title=\"Send an email\">Feel free to contact me</a> if you are looking for a website or are interested in working together.</p>"
  featured:
    - title: Websites
      body: "Looking for a new website or an update to an old website? I execute all projects quickly and at a competitive price according to all clients' wishes. The new website is responsive, beautiful, search engine optimized, quick and easy to update."
      img: websites
      img_alt: "Responsive and beautiful website for company"
    - title: Web stores
      body: "Boost sales with Tuspe's versatile online store platform at competitive prices. The web store is customized to meet the customer's needs, with unlimited language, effective campaigns, and of course the most common payment and shipping options."
      img: webshops
      img_alt: "Boost sales with better online store"
    - title: Ratsukko
      body: "Too many phone calls and emails on bookings as a stable entrepreneur? No worries! Reservation calendar Ratsukko saves time and effort by providing a real-time system where customers can take care of bookings and cancellations on their own."
      img: ratsukko
      img_alt: "Reservation calendar Ratsukko saves time, effort and money!"
    - title: Sport Clubs
      body: "Our website for sport clubs have versatile features and it's suitable for sports clubs of all sizes. You can even have web store included. Editing is easy and fast and we have automated as many functions as possible. Are you ready to join the winning team?"
      img: sport
      img_alt: "Versatile homepage for a sports club"
    - title: Better Search Results
      body: "All projects are technically optimized for search engines and visitors, but content is most important and must be unique! I offer tips on how to better optimize your website and your content if needed. Also recommend keyword research."
      img: seo
      img_alt: "Learn about technical search engine optimization and keyword research"
    - title: Hosting
      body: "Our dedicated servers are protected from technical problems and all your data is backed up twice a day to an external server. A secure and reliable home for your website, plus all security updates for modules and small changes to your website."
      img: hosting
      img_alt: "A secure and reliable home for your website"
  atom: "Recent additions to source code"
  footer:
    left: "New project?"
    mid: "Interested? Contact me and let's discuss how I can help."

footer: "Living, learning, &amp; leveling up<br>one day at a time."
include:
  - _redirects
  - _headers

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md